export const styles : any = {
    header1: {fontSize: 24, bold: true},
    header2: {fontSize: 20, bold: true},
    header3: {fontSize: 18, bold: true},
    header4: {fontSize: 16, bold: true},
    paragraph: {fontSize: 12, color: '#333'},
    unorderedList: {fontSize: 12, color: '#333'},
    orderedList: {fontSize: 12, color: '#333'},
    tableHeader: {fontSize: 12, bold: true, fillColor: '#eeeeee'},
    tableCell: {fontSize: 12},
    noteTitle: {fontSize: 14, bold: true},
    noteContent: {fontSize: 12, color: '#333'},
    inlineComponent: {fontSize: 12, bold: true, color: '#007BFF'},
    iconStyle: {fontSize: 14, bold: true},
}